### ISSUE TITLE
Rails 5 migration error

### ISSUE THREAD

**Issue by nbashaw** [jmfederico/draftsman#73]
The first line of the migration file it generate when you run `rails g draftsman:install` looks like this:

```ruby
class CreateDrafts < ActiveRecord::Migration
```

If you run `rake db:migrate` rails throws an error:

```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

class CreateDrafts < ActiveRecord::Migration[4.2]
```
I think the error message says it all! The code outputted by the generator should not directly inherit from `ActiveRecord::Migration`.

**Comment by huskylengcb** [comment]
`class CreateDrafts < ActiveRecord::Migration`changes`class CreateDrafts < ActiveRecord::Migration[5.1]`

**Comment by huskylengcb** [comment]
`class CreateDrafts < ActiveRecord::Migration`
changes
`class CreateDrafts < ActiveRecord::Migration[5.1]`

**Comment by jmfederico** [comment]
Actually, migrations were created for version 4.2, so you should change it to:
```ruby
class CreateDrafts < ActiveRecord::Migration[4.2]
```
