### ISSUE TITLE
Draft#publish! should not skip model validations

### ISSUE THREAD

**Issue by Looooong** [jmfederico/draftsman#75]
Or at least `publish!` should receive arguments that will be passed to `save`.

I have to validate that the record has to meet certain criteria when it is published but not when it is drafted.

**Comment by Looooong** [comment]
I will make a PR for this by adding `save_options` with default `validate: false` to `draftsman_options` of the model class. How should I test this?

**Comment by Looooong** [comment]
I have made a PR at #76 . Hope that will help.

**Comment by jmfederico** [comment]
Thanks for the PR! Makes sense.

Will review and commit.

**Comment by jmfederico** [comment]
Merged.
