### ISSUE TITLE
Project status - new steward needed

### ISSUE THREAD

**Issue by jmfederico** [jmfederico/draftsman#85]
**Draftsman** is looking for a new Steward.
I no longer have the time to keep developing it.

Anyone who is interested in taking over please let me know.

**Comment by copasetickid** [comment]
Hi 👋  @jmfederico  what exactly would go into taking this over? I'm considering using this for a feature and if I do it would make sense to maintain then. Otherwise, I'm considering using a state machine to implement my own solution as I have some concerns over the publish logic for associated models in this gem

https://github.com/jmfederico/draftsman/issues/84#issuecomment-460271169

**Comment by jmfederico** [comment]
Hi 👋🏽 @copasetickid !

Well, to be honest I think all is needed is a person with genuine interest on taking over the project. If you are interested I would transfer ownership immediately.

I would also give you access project in RubyGems: https://rubygems.org/gems/draftsman

I honestly think this is a great gem, and served me well while I needed it. Hopefully you can keep it useful for you and others.

Let me know!

**Comment by yasser-sobhy** [comment]
Hello @jmfederico I am interested too. I don't use this gem right now, but I was looking for a ruby project to contribute to and I think this gem is a really good one.

Please note that I may need your help to document few methods in the codebase which I didn't understand what they're doing. Please also note that I have contributed the multiple drafts feature https://github.com/jmfederico/draftsman/pull/71 (still not merged).

Thnaks

**Comment by copasetickid** [comment]
@jmfederico  Sorry for the delay.  Yes, I'm still interested in taking over the project.  

Would you able to provide any guidance while I get up to speed with the codebase? Is there a roadmap of features you were thinking of adding to this project or things that needed to be refactored? 

Thanks 😄

**Comment by jmfederico** [comment]
@copasetickid is the new maintainer for the project.

@yasser-sobhy I appreciate your interest 👍🏽. @copasetickid came first to the issue, so I gave her priority.

**Comment by cyri113** [comment]
Hello, is this project actively maintained?

**Comment by nduplessis** [comment]
Hi @copasetickid

Are you still interested in maintaining this gem?
